services:
  urler:
    container_name: urler
    build: .
    ports:
      - '8080:8080'
    environment:
      BASE_URL: "http://localhost"
      DATABASE: /urler/data/
      LOG_FORMAT: "json" # json, text, maybe more in the future

      # Future
      # METRICS: "true" # true / false
      # METRICS_PORT: "<port>" # A non-sudo port (NOT 0-1023)

