services:
  urler:
    container_name: urler
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./data:/urler/data
    environment:
      BASE_URL: "http://localhost"
      PORT: "8080"
      DATA_FOLDER: "/urler/data"
      LOG_FORMAT: "text" # json, text, maybe more in the future
      DEBUG: "true"
      # Future
      # METRICS: "true" # true / false
      # METRICS_PORT: "<port>" # A non-sudo port (NOT 0-1023)
