error_log /urler/logs/error.log error;
pid /urler/tmp/nginx.pid;
worker_processes 1;

env DATA_FOLDER;
env BASE_URL;
env PORT;
env LOG_FORMAT;
env DEBUG;

events {
  worker_connections 1024;
}

http {
  access_log /urler/logs/access.log combined;

  client_body_temp_path /urler/tmp/client_body 1 2;
  proxy_temp_path /urler/tmp/proxy;
  fastcgi_temp_path /urler/tmp/fastcgi;
  uwsgi_temp_path /urler/tmp/uwsgi;
  scgi_temp_path /urler/tmp/scgi;

  init_by_lua_block {
    local log = require("utils.logging")
    local ENV = require("utils.env")
    log.info("Server running on " .. ENV.BaseUrl)
  }

  server {
    listen 8080;
    server_name _;
    location = / {
      default_type text/html;
      content_by_lua_block {
        local headers = ngx.req.get_headers()
        ngx.say("Hello Mister " .. ngx.req.get_headers()["user-agent"])
      }
    }
  }
}
